---
- name: check if files allready exists
  stat:
    path: /etc/systemd/system/docker.service.d/kolla.conf
  register: file_result

- name: create docker systemd nested folder
  command: mkdir -p /etc/systemd/system/docker.service.d
  when: file_result.stat.exists == False

- name: create docker shared-mount systemd file
  copy: src=kolla.conf dest=/etc/systemd/system/docker.service.d/kolla.conf owner=root group=root mode=0644
  when: file_result.stat.exists == False

- name: systemd daemon-reload
  shell: /usr/bin/systemctl daemon-reload
  when: file_result.stat.exists == False

- name: restart dockerd
  shell: /usr/bin/systemctl restart docker
  when: file_result.stat.exists == False

- name: install python pip
  yum:
    name: python-pip
    state: latest

- name: install python-docker package
  yum:
    name: python-docker-py
    state: latest
